version: "3.5"
services:
  app-web-static:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web-static
                                      
  app-web-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web-ui
