version: "3.7"
services:
  app-web-static:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web-static
  app-web-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web-ui
  app-haproxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-haproxy
    ports:
     - "9000:9000"
    depends_on:
     - "app-web-ui"
     - "app-web-static"
